# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('拉伸模板.pptx', '.'),
        ('VDA弯曲角模板.pptx', '.'),
    ],
    hiddenimports=[
        'tkinterdnd2',
        'win32com.client',
        'pythoncom',
        'pywintypes',
        'pandas',
        'openpyxl',
        'pptx',
        'pdfplumber',
        'PIL',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch',
        'torchvision',
        'tensorflow',
        'scipy',
        'numpy.core._dotblas',
        'matplotlib',
        'IPython',
        'jupyter',
        'notebook',
        'pytest',
        'sphinx',
        'docutils',
        'jedi',
        'parso',
        'pyarrow',
        'numba',
        'llvmlite',
        'boto3',
        'botocore',
        's3fs',
        'fsspec',
        'tables',
        'numexpr',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

splash = Splash(
    'assets/startup_splash.png',
    binaries=a.binaries,
    datas=a.datas,
    text_pos=(44, 260),
    text_size=12,
    text_font='Microsoft YaHei UI',
    text_color='#475569',
    text_default='正在解压程序组件...',
    minify_script=True,
    always_on_top=True,
)

exe = EXE(
    pyz,
    splash,
    a.scripts,
    a.binaries,
    a.datas,
    splash.binaries,
    [],
    name='育材堂报告助手V3.16',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
